---
- name: Update apt cache
  apt: update_cache=yes
  tags:
    - dependencies

- name: Upgrade all safe packages
  apt: upgrade=safe
  tags:
    - dependencies

- name: Install necessities and nice-to-haves
  apt: pkg={{ ubermail_packages_base }} state=present
  tags:
    - dependencies

- name: timezone - configure /etc/timezone
  copy:
    content: "{{ common_timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: common_timezone_config

- name: timezone - Set localtime to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime
  when: common_timezone_config.changed

- name: timezone - reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: common_timezone_config.changed

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

- name: "Create decrypted directory (even if encfs isn't used)"
  file: state=directory path=/decrypted

- name: Set decrypted directory permissions
  file: state=directory path=/decrypted group=mail mode=0775

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present

- include: encfs.yml tags=encfs
  when: encfs_enabled
- include: users.yml tags=users
- include: apache.yml tags=apache
- include: ssl.yml tags=ssl
- include: letsencrypt.yml tags=letsencrypt
- include: ufw.yml tags=ufw
- include: security.yml tags=security
- include: chrony.yml tags=chrony
- include: google_auth.yml tags=google_auth
- include: postgres.yml


- include: postfix.yml tags=postfix
- include: dovecot.yml tags=dovecot
- include: solr.yml tags=solr
- include: sieve.yml
  when:  mail_virtual_sieves | length > 0
- include: rspamd.yml tags=rspamd
- include: checkrbl.yml tags=checkrbl
- include: z-push.yml tags=zpush
- include: autoconfig.yml tags=autoconfig
- include: imapsync.yml tags=imapsync

- include: roundcube.yml tags=roundcube

- include: monit.yml tags=monit
- include: logwatch.yml tags=logwatch
- include: collectd.yml tags=collectd

- set_fact: mxip="{{ lookup('dig', ansible_host) }}"
- shell: |
    echo '{{ mxip }}' | awk 'BEGIN{FS="."}{print $4"."$3"."$2"."$1".in-addr.arpa"}'
  register: revip

- name: Ensure /opt/ubermail exists
  file: state=directory path="/opt/ubermail" group=www-data owner=root

- include: summary.yml
  with_items: "{{ mail_virtual_domains }}"
  loop_control:
    loop_var: outer_item

