---
- name: Install Postgres
  apt: pkg={{ ubermail_packages_postgres }} state=present
  tags:
    - dependencies

- name: Ensure Postgres is started upon initial deployment
  systemd: name=postgresql state=started

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes
