---
# Installs and configures the Rspamd spam/virus filtering system.

- name: Ensure repository key for Rspamd is in place
  apt_key: url=https://rspamd.com/apt-stable/gpg.key state=present
  tags:
    - dependencies

- name: Add Rspamd repository
  apt_repository: repo="deb https://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"
  tags:
    - dependencies

- name: Install Rspamd and Redis
  apt: pkg={{ ubermail_packages_rspamd }} state=present update_cache=yes
  tags:
    - dependencies

- name: "Test redis password strength"
  fail: msg="Password too weak, use 32 chars or more."
  when: mail_rspamd_password | length < 32

- name: Get the rspamd password hash
  command: "rspamadm pw -p {{ mail_rspamd_password }}"
  register: rspamadm_pw

- debug: msg="{{ rspamadm_pw.stdout }}"

- name: "Configure rspamd/local.d/* files"
  template: src="etc_rspamd_local.d_{{ item }}.j2" dest="/etc/rspamd/local.d/{{ item }}"
  with_items:
    - "worker-controller.inc"
    - "worker-proxy.inc"
    - "greylist.conf"
    - "redis.conf"
    - "mime_types.conf"
    - "replies.conf"
    - "milter_headers.conf"
    - "antivirus.conf"
    - "options.inc"
    - "dmarc.conf"
    - "asn.conf"
    - "greylist.conf"
    - "ip_score.conf"
    - "metrics.conf"
    - "milter_headers.conf"
    - "multimap.conf"
    - "mx_check.conf"
    - "phishing.conf"
    - "surbl.conf"
    - "url_reputation.conf"
    - "url_tags.conf"
  notify: restart rspamd

- name: "Configure local blacklist/whitelist multimap files"
  template: src="etc_rspamd_local.d_{{ item }}.j2" dest="/etc/rspamd/local.d/{{ item }}" mode=0646
  with_items:
    - "local_bl_from.map.inc"
    - "local_bl_ip.map.inc"
    - "local_bl_rcpt.map.inc"
    - "local_wl_from.map.inc"
    - "local_wl_ip.map.inc"
    - "local_wl_rcpt.map.inc"
  notify: restart rspamd

- name: Copy DKIM configuration into place
  copy: src=etc_rspamd_override.d_dkim_signing.conf dest=/etc/rspamd/override.d/dkim_signing.conf owner=root group=root mode="0644"
  notify: restart rspamd

- name: Create dkim key directory
  file: path=/var/lib/rspamd/dkim state=directory owner=_rspamd group=_rspamd

- name: Generate DKIM keys
  shell: rspamadm dkim_keygen -s default -d {{ item.name }} -k {{ item.name }}.default.key > {{ item.name }}.default.txt
  args:
    creates: /var/lib/rspamd/dkim/{{ item.name }}.default.key
    chdir: /var/lib/rspamd/dkim/
  with_items: "{{ mail_virtual_domains }}"

- name: Stop clamav-freshclam
  service: name=clamav-freshclam state=stopped enabled=yes

- name: "Update virus signature files (can fail if freshclam daemon is already running)"
  shell: "freshclam"
  ignore_errors: yes


- name: "Configure Redis"
  template: src="etc_redis_redis.conf.j2" dest="/etc/redis/redis.conf"

- name: Start clamav-daemon
  service: name=clamav-daemon state=started enabled=yes

- name: Start clamav-freshclam
  service: name=clamav-freshclam state=started enabled=yes

- name: Start redis
  service: name=redis-server state=started enabled=yes

- name: Start unbound
  service: name=unbound state=restarted enabled=yes

- name: Start rspamd systemd listener
  service: name=rspamd state=started enabled=yes

- name: Enable proxy modules (rspamd gui)
  apache2_module:
    state: present
    name: "{{ item }}"
  loop:
   - proxy
   - proxy_http

- name: "Update DNSSEC Root key and reload Unbound service"
  shell: "unbound-anchor -a /var/lib/unbound/root.key"
  retries: 3
  delay: 2
