---

- name: "Ensure path to sieve script exists"
  file:
    path: "/decrypted/{{ item.domain }}/{{ item.account }}/sieve"
    state: directory
    owner: vmail
    group: vmail
    mode: 0700
  with_items: "{{ mail_virtual_sieves }}"

- include: sieve_loop.yml
  with_items: "{{ mail_virtual_sieves }}"
  loop_control:
    loop_var: outer_item
  when: mail_virtual_sieves and mail_virtual_sieves > 0

- name: "Ensure sieve file has what it takes"
  blockinfile:
    path: "/decrypted/{{ item.domain }}/{{ item.account }}/sieve/managesieve.sieve"
    block: |
      {% for i in item.rule %}
      # rule:[{{ i.name }}]
      if {{ i.cond }} {
           {{ i.acts }}
      }
      {% endfor %}
  with_items: "{{ mail_virtual_sieves }}"

