---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart chrony
  service: name=chrony state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: restart dovecot
  service: name=dovecot state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart solr
  service: name=tomcat8 state=restarted

- name: import sql postfix
  action: shell PGPASSWORD='{{ mail_db_password }}' psql -h localhost -d {{ mail_db_database }} -U {{ mail_db_username }} -f /etc/postfix/import.sql --set ON_ERROR_STOP=1
  notify: restart postfix

- name: restart rspamd
  service: name=rspamd state=restarted

- name: restart monit
  service: name=monit state=restarted

- name: restart collectd
  service: name=collectd state=restarted

